apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: petclinic-deploy-dev
spec:
  params:
  - name: DEV_PROJECT
    type: string
    default: demo-dev
    description: The DEV namespace where application is deployed
  workspaces:
  - name: local-maven-repo
  resources:
  - name: app-git
    type: git
  - name: config-git
    type: git
  - name: tests-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: unit-tests
    taskRef:
      name: maven
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    resources:
      inputs:
      - name: source
        resource: app-git
    params:
    - name: GOALS
      value: ["package"]
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
  - name: release-app
    taskRef:
      name: maven
    runAfter:
      - unit-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    resources:
      inputs:
      - name: source
        resource: app-git
    params:
    - name: GOALS
      value:
      - deploy
      - -DskipTests=true
      - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
      - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
  - name: code-analysis
    taskRef:
      name: maven
    runAfter:
      - unit-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    resources:
      inputs:
      - name: source
        resource: app-git
    params:
    - name: GOALS
      value:
      - install
      - sonar:sonar
      - -Dsonar.host.url=http://sonarqube:9000
      - -Dsonar.userHome=/tmp/sonar
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
  - name: dependency-report
    taskRef:
      name: dependency-report
    runAfter:
      - unit-tests
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    resources:
      inputs:
      - name: source
        resource: app-git
    params:
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
  - name: build-image
    taskRef:
      name: s2i-java-8-pr
      kind: ClusterTask
    runAfter:
      - release-app
      - code-analysis
      - dependency-report
    params:
      - name: TLSVERIFY
        value: "false"
      - name: MAVEN_MIRROR_URL
        value: http://nexus:8081/repository/maven-public/
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: deploy-dev
    taskRef:
      name: deploy-app
    runAfter:
      - build-image
    params:
    - name: DEPLOYMENT_NAME
      value: spring-petclinic
    - name: CONTAINER_NAME
      value: spring-petclinic
    - name: NAMESPACE
      value: $(params.DEV_PROJECT)
    - name: IMAGE
      value: spring-petclinic:latest
    - name: KUSTOMIZE_OVERLAY_DIR
      value: environments/dev
    resources:
      inputs:
      - name: config
        resource: config-git
  - name: int-test
    taskRef:
      name: openshift-client
    runAfter:
      - deploy-dev
    params:
    - name: COMMANDS
      value: |
          sleep $(($RANDOM % 40 + 20))
  - name: perf-test
    taskRef:
      name: gatling
    runAfter:
      - deploy-dev
    params:
      - name: APP_URL
        value: "http://spring-petclinic.$(params.DEV_PROJECT).svc.cluster.local:8080"
    resources:
      inputs:
      - name: simulations
        resource: tests-git
