apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-deploy-dev-run-
spec:
  pipelineRef:
    name: petclinic-deploy-dev
  resources:
  - name: app-git
    resourceRef:
      name: petclinic-git
  - name: config-git
    resourceRef:
      name: petclinic-config-git
  - name: tests-git
    resourceRef:
      name: petclinic-tests-git
  - name: app-image
    resourceRef:
      name: petclinic-image
  workspaces:
  - name: local-maven-repo
    emptyDir: {}
